#ifndef BAIDU_CORE_LIBRARY_GLOBAL_HPP
#define BAIDU_CORE_LIBRARY_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(BAIDU_CORE_LIBRARY_LIBRARY)
#  define BAIDU_CORE_LIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BAIDU_CORE_LIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BAIDU_CORE_LIBRARY_GLOBAL_HPP
